import tkinter
window = tkinter.Tk()
window.geometry('260x210')
window.configure(bg='black')
window.title("Prevent Corona")
def changeText():
    button['text']="R = "+str((int(ip.get())/int(dp.get()))/(int(rp.get())/int(dp.get())))
tkinter.Label(text="Determination of Basic Reproduction Number:", bg='black', fg='white').grid(row=0)
tkinter.Label(text="Days have been passed:", bg='black', fg='white').grid(row=1, column=0)
dp=tkinter.Entry()
dp.grid(row=2)
tkinter.Label(text="No. of infected people:", bg='black', fg='white').grid(row=3, column=0)
ip=tkinter.Entry()
ip.grid(row=4)
tkinter.Label(text="No. of recovered people:", bg='black', fg='white').grid(row=5, column=0)
rp=tkinter.Entry()
rp.grid(row=6)
button= tkinter.Button(window, text="Submit", bg='black', fg='white', command=changeText)
button.grid(row=7)
tkinter.Label(text="R less than 1 is safe", bg='black', fg='white').grid(row=8)
window.mainloop()